version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    env_file:
      - .production.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/root/.pgadmin
    env_file:
      - .production.env
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongovolume:/data/db/mongo
    ports:
      - "27017:27017"
    restart: always
#    restart: on-failure
volumes:
  mongovolume: